name: CI-CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker build -t "$TAG_COMMIT" -t "$TAG_LATEST" .

      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker push "$TAG_COMMIT"
          docker push "$TAG_LATEST"

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH client and Netcat
        run: |
          sudo apt-get update \
            && sudo apt-get install -y openssh-client netcat-openbsd

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH target
        run: |
          echo "Using SERVER_IP = ${{ secrets.SERVER_IP }}"
          nc -z -v -w5 ${{ secrets.SERVER_IP }} 443 && echo "Port 443 open" || echo "Port 443 closed"

      - name: Add server to known_hosts (allow failures)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 443 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || true

      - name: Deploy via SSH on port 443
        env:
          IMAGE_NAME: "ghcr.io/kaka556kevin/2305017"
        run: |
          ssh -vvv -p 443 -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull $IMAGE_NAME:${{ github.sha }}
            docker rm -f my-app || true
            docker run -d -p 80:80 --name my-app $IMAGE_NAME:${{ github.sha }}
          EOF
