name: CI-CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker build -t "$TAG_COMMIT" -t "$TAG_LATEST" .

      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker push "$TAG_COMMIT"
          docker push "$TAG_LATEST"

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH client and Netcat
        run: |
          sudo apt-get update \
            && sudo apt-get install -y openssh-client netcat-openbsd

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Optional: Test SSH connectivity
        run: |
          echo "Checking SSH port on ${{ secrets.SERVER_IP }}..."
          if ! nc -z ${{ secrets.SERVER_IP }} 22; then
            echo "Warning: port 22 unreachable, continuing to action step may still retry."
          fi

      - name: Deploy via SSH Action
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          script: |
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
            TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
            docker pull "$TAG_COMMIT"
            docker rm -f my-app || true
            docker run -d -p 80:80 --name my-app "$TAG_COMMIT"
