name: CI-CD Pipeline

# ------------------------------------------------------------
# 1) Tambahkan blok permissions agar GITHUB_TOKEN dapat menulis ke GHCR
# ------------------------------------------------------------
permissions:
  contents: read             # Agar Actions bisa checkout kode
  packages: write            # Agar GITHUB_TOKEN bisa push image ke GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker build -t "$TAG_COMMIT" -t "$TAG_LATEST" .

      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"
          TAG_LATEST="${IMAGE_NAME}:latest"
          docker push "$TAG_COMMIT"
          docker push "$TAG_LATEST"

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key for Deployment
        run: |
          mkdir -p "$/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> "$HOME/.ssh/known_hosts"
        shell: bash

      - name: Deploy via SSH
        run: |
          IMAGE_NAME="ghcr.io/kaka556kevin/2305017"
          TAG_COMMIT="${IMAGE_NAME}:${{ github.sha }}"

          ssh -i "$HOME/.ssh/id_rsa" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \
             docker pull $TAG_COMMIT && \
             docker rm -f my-app || true && \
             docker run -d -p 80:80 --name my-app $TAG_COMMIT"
        shell: bash
