name: CI-CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/kaka556kevin/2305017

jobs:
  build-and-push:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          TAG_COMMIT="${{ env.IMAGE_NAME }}:${{ github.sha }}"
          TAG_LATEST="${{ env.IMAGE_NAME }}:latest"
          docker build \
            -t "$TAG_COMMIT" \
            -t "$TAG_LATEST" \
            .

      - name: Push Docker image
        run: |
          TAG_COMMIT="${{ env.IMAGE_NAME }}:${{ github.sha }}"
          TAG_LATEST="${{ env.IMAGE_NAME }}:latest"
          docker push "$TAG_COMMIT"
          docker push "$TAG_LATEST"

  deploy:
    name: Deploy to Production Server
    runs-on: [self-hosted, linux, x64]
    needs: build-and-push

    steps:
      # (1) Pastikan SSH client & netcat terpasang di runner
      - name: Install SSH client & Netcat
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client netcat-openbsd

      # (2) Tulis private key kita ke ~/.ssh/id_rsa dan chmod-nya
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # (3) Tunggu sampai port SSH (2222) di server produksi terbuka
      - name: Wait for SSH to open on port 2222 (up to 50s)
        run: |
          echo "Checking SSH port 2222 on ${{ secrets.SERVER_IP }}..."
          for i in {1..5}; do
            if nc -z ${{ secrets.SERVER_IP }} 2222; then
              echo "✅ SSH port 2222 is open!"
              exit 0
            else
              echo "⏳ Port 2222 closed (attempt $i/5). Retrying in 10s..."
              sleep 10
            fi
          done
          echo "❌ SSH port 2222 still closed after 5 attempts. Aborting."
          exit 1

      # (4) Tambahkan server ke known_hosts agar tidak muncul prompt security
      - name: Add server to known_hosts (allow failures)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2222 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || true

      # (5) SSH sekali saja ke server, lalu jalankan perintah Docker
      - name: Deploy via SSH (port 2222)
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=10 \
              -p 2222 \
              deployer@${{ secrets.SERVER_IP }} <<'EOF'
            # 5.a) Login ke GHCR supaya `docker pull` bisa sukses
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
              -u ${{ github.actor }} --password-stdin

            # 5.b) Hentikan dan hapus container lama (jika ada)
            docker rm -f my-app || true

            # 5.c) Pull image baru (commit SHA)
            docker pull "${{ env.IMAGE_NAME }}:${{ github.sha }}"

            # 5.d) Jalankan container baru pada port 443 (bukan 80)
            docker run -d -p 443:80 --name my-app "${{ env.IMAGE_NAME }}:${{ github.sha }}"

            # Catatan:
            # - Jika Anda ingin pakai port 22 (bukan 80), ganti -p 443:80 menjadi -p 22:80
            # - Jika Anda ingin pakai port 2222, ganti -p 443:80 menjadi -p 2222:80
          EOF
